#!/bin/bash

HYPR_CONF="$HOME/.config/hypr/hyprland.conf"

# Backup original file
cp "$HYPR_CONF" "$HYPR_CONF.bak"
echo "Backup created: $HYPR_CONF.bak"

# Remove 'autogenerated = 1' line
sed -i '/^\s*autogenerated\s*=\s*1\s*#/d' "$HYPR_CONF"

# Replace 'monitor=,preferred,auto,auto' with desired monitor config
if grep -q '^monitor=,preferred,auto,auto' "$HYPR_CONF"; then
    sed -i 's/^monitor=,preferred,auto,auto/monitor=eDP-1,1920x1080@60,0x0,1/' "$HYPR_CONF"
else
    echo "monitor=eDP-1,1920x1080@60,0x0,1" | tee -a "$HYPR_CONF" > /dev/null
fi

echo "Hyprland config updated successfully."
