pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

// Colors.qml — Material Design 3 color provider
//
// Loads colors from ~/.config/quickshell/colors.json (generated by matugen).
// Uses plain QtObject children (not inline component types) to avoid
// property cache creation issues during singleton property lookups.

Singleton {
    id: root

    // Public API — access via Colors.m3.surface, Colors.base16.base00, etc.
    property alias m3: _md3
    property alias md3: _md3
    property alias base16: _base16
    property alias palette: _palette

    // Parse JSON and apply to child objects
    function load(jsonText: string): void {
        try {
            const data = JSON.parse(jsonText)

            if (data.md3) {
                for (const [key, value] of Object.entries(data.md3)) {
                    if (_md3.hasOwnProperty(key))
                        _md3[key] = value
                }
            }

            if (data.palette) {
                for (const [key, value] of Object.entries(data.palette)) {
                    if (_palette.hasOwnProperty(key))
                        _palette[key] = value
                }
            }

            if (data.base16) {
                for (const [key, value] of Object.entries(data.base16)) {
                    if (_base16.hasOwnProperty(key))
                        _base16[key] = value
                }
            }
        } catch (e) {
            console.error("[Colors] Failed to parse colors.json:", e)
        }
    }

    FileView {
        path: Quickshell.env("HOME") + "/.config/quickshell/colors.json"
        watchChanges: true
        blockLoading: true
        onFileChanged: reload()
        onLoaded: root.load(text())
    }

    // ── MD3 colors ───────────────────────────────────────────────────────────
    QtObject {
        id: _md3
        property string background: "#131318"
        property string error: "#ffb4ab"
        property string error_container: "#93000a"
        property string inverse_on_surface: "#303036"
        property string inverse_primary: "#585992"
        property string inverse_surface: "#e4e1e9"
        property string on_background: "#e4e1e9"
        property string on_error: "#690005"
        property string on_error_container: "#ffdad6"
        property string on_primary: "#292a60"
        property string on_primary_container: "#e1dfff"
        property string on_primary_fixed: "#14134a"
        property string on_primary_fixed_variant: "#404178"
        property string on_secondary: "#2f2f42"
        property string on_secondary_container: "#e2e0f9"
        property string on_secondary_fixed: "#1a1a2c"
        property string on_secondary_fixed_variant: "#454559"
        property string on_surface: "#e4e1e9"
        property string on_surface_variant: "#c7c5d0"
        property string on_tertiary: "#322c42"
        property string on_tertiary_container: "#eddcff"
        property string on_tertiary_fixed: "#1d172d"
        property string on_tertiary_fixed_variant: "#494259"
        property string outline: "#918f9a"
        property string outline_variant: "#46464f"
        property string primary: "#c3c3ff"
        property string primary_container: "#404178"
        property string primary_fixed: "#e1dfff"
        property string primary_fixed_dim: "#c3c3ff"
        property string scrim: "#000000"
        property string secondary: "#c6c4dd"
        property string secondary_container: "#454559"
        property string secondary_fixed: "#e2e0f9"
        property string secondary_fixed_dim: "#c6c4dd"
        property string shadow: "#000000"
        property string surface: "#131318"
        property string surface_bright: "#39383f"
        property string surface_container: "#201f25"
        property string surface_container_high: "#2a2930"
        property string surface_container_highest: "#35343b"
        property string surface_container_low: "#1c1b21"
        property string surface_container_lowest: "#0e0e13"
        property string surface_dim: "#131318"
        property string surface_tint: "#c3c3ff"
        property string surface_variant: "#46464f"
        property string tertiary: "#ccc0e8"
        property string tertiary_container: "#494259"
        property string tertiary_fixed: "#eddcff"
        property string tertiary_fixed_dim: "#ccc0e8"
    }

    // ── Palette colors ───────────────────────────────────────────────────────
    QtObject {
        id: _palette
        property string error0: "#000000"
        property string error5: "#1a0002"
        property string error10: "#2d0004"
        property string error15: "#3d0007"
        property string error20: "#4e0a0a"
        property string error25: "#5c1414"
        property string error30: "#6b1e1e"
        property string error35: "#7a2929"
        property string error40: "#893434"
        property string error50: "#a64c4c"
        property string error60: "#c46464"
        property string error70: "#e37e7e"
        property string error80: "#ffb4ab"
        property string error90: "#ffdad6"
        property string error95: "#ffedea"
        property string error98: "#fff8f7"
        property string error99: "#fffbff"
        property string error100: "#ffffff"

        property string neutral0: "#000000"
        property string neutral5: "#121116"
        property string neutral10: "#1c1b21"
        property string neutral15: "#27262b"
        property string neutral20: "#313036"
        property string neutral25: "#3c3b41"
        property string neutral30: "#48474d"
        property string neutral35: "#535258"
        property string neutral40: "#5f5e65"
        property string neutral50: "#78777d"
        property string neutral60: "#929197"
        property string neutral70: "#adabb2"
        property string neutral80: "#c8c6cd"
        property string neutral90: "#e4e1e9"
        property string neutral95: "#f3f0f7"
        property string neutral98: "#fcf8ff"
        property string neutral99: "#fffbff"
        property string neutral100: "#ffffff"

        property string neutral_variant0: "#000000"
        property string neutral_variant5: "#121117"
        property string neutral_variant10: "#1d1b22"
        property string neutral_variant15: "#27262d"
        property string neutral_variant20: "#323037"
        property string neutral_variant25: "#3d3b43"
        property string neutral_variant30: "#48464e"
        property string neutral_variant35: "#54525a"
        property string neutral_variant40: "#605d66"
        property string neutral_variant50: "#79767f"
        property string neutral_variant60: "#938f99"
        property string neutral_variant70: "#aeaab4"
        property string neutral_variant80: "#c9c5cf"
        property string neutral_variant90: "#e6e0ec"
        property string neutral_variant95: "#f4eefa"
        property string neutral_variant98: "#fdf7ff"
        property string neutral_variant99: "#fffbff"
        property string neutral_variant100: "#ffffff"

        property string primary0: "#000000"
        property string primary5: "#0b0a3f"
        property string primary10: "#14134a"
        property string primary15: "#1e1d55"
        property string primary20: "#292a60"
        property string primary25: "#34356c"
        property string primary30: "#3f4078"
        property string primary35: "#4b4b84"
        property string primary40: "#575791"
        property string primary50: "#706fab"
        property string primary60: "#8a89c6"
        property string primary70: "#a5a3e2"
        property string primary80: "#c3c3ff"
        property string primary90: "#e1dfff"
        property string primary95: "#f2efff"
        property string primary98: "#fbf8ff"
        property string primary99: "#fffbff"
        property string primary100: "#ffffff"

        property string secondary0: "#000000"
        property string secondary5: "#100f21"
        property string secondary10: "#1a1a2c"
        property string secondary15: "#252436"
        property string secondary20: "#302f41"
        property string secondary25: "#3b3a4c"
        property string secondary30: "#464558"
        property string secondary35: "#525164"
        property string secondary40: "#5e5d70"
        property string secondary50: "#777589"
        property string secondary60: "#918fa3"
        property string secondary70: "#aca9bf"
        property string secondary80: "#c7c4db"
        property string secondary90: "#e3e0f8"
        property string secondary95: "#f2efff"
        property string secondary98: "#fbf8ff"
        property string secondary99: "#fffbff"
        property string secondary100: "#ffffff"

        property string tertiary0: "#000000"
        property string tertiary5: "#120c22"
        property string tertiary10: "#1d172d"
        property string tertiary15: "#282138"
        property string tertiary20: "#332c43"
        property string tertiary25: "#3e374e"
        property string tertiary30: "#4a435a"
        property string tertiary35: "#564e66"
        property string tertiary40: "#625a73"
        property string tertiary50: "#7b728c"
        property string tertiary60: "#968ca7"
        property string tertiary70: "#b1a6c2"
        property string tertiary80: "#cdc1de"
        property string tertiary90: "#e9dcfb"
        property string tertiary95: "#f6eeff"
        property string tertiary98: "#fdf7ff"
        property string tertiary99: "#fffbff"
        property string tertiary100: "#ffffff"
    }

    // ── Base16 colors ────────────────────────────────────────────────────────
    QtObject {
        id: _base16
        property string base00: "#131318"
        property string base01: "#1c1b21"
        property string base02: "#46464f"
        property string base03: "#918f9a"
        property string base04: "#c7c5d0"
        property string base05: "#e4e1e9"
        property string base06: "#f3f0f7"
        property string base07: "#fcf8ff"
        property string base08: "#ffb4ab"
        property string base09: "#c3c3ff"
        property string base0a: "#e1dfff"
        property string base0b: "#c6c4dd"
        property string base0c: "#ccc0e8"
        property string base0d: "#c3c3ff"
        property string base0e: "#ccc0e8"
        property string base0f: "#ffb4ab"
    }
}
