cursor            #8dcff1
cursor_text_color #003547

foreground            #dfe3e7
background            #0a0f12
selection_foreground  #1f333d
selection_background  #b4cad6
url_color             #b4cad6

#: black 000000 767676
color0  #0f1417
color8  #303539
#: red cc0403 f2201f
color1  #9a3b23
color9  #e08b76
#: green 19cb00 23fd00
color2  #b4cad6
color10 #d0e6f3
#: yellow cecb00 fffd00
color3  #c8c2ea
color11 #e4dfff
#: blue 0d73cc 1a8fff
color4  #004d66
color12 #8dcff1
#: magenta cb1ed1 fd28ff
color5  #364954
color13 #b4cad6
#: cyan 0dcdcd 14ffff
color6  #464364
color14 #c8c2ea
#: white dddddd ffffff
color7  #c0c7cd
color15 #dfe3e7

mark1_foreground #001e2b
mark1_background #c0e8ff
mark2_foreground #091e27
mark2_background #d0e6f3
mark3_foreground #1b1736
mark3_background #e4dfff

active_tab_foreground #003547
active_tab_background #8dcff1
inactive_tab_foreground #c0e8ff
inactive_tab_background #004d66

active_border_color #8dcff1
inactive_border_color #003547
# bell_border_color #ff5a00
