cursor            #ffb4aa
cursor_text_color #561e18

foreground            #f1dedc
background            #140c0b
selection_foreground  #442926
selection_background  #e7bdb7
url_color             #e7bdb7

#: black 000000 767676
color0  #1a1110
color8  #3d3231
#: red cc0403 f2201f
color1  #0e8476
color9  #40ebd6
#: green 19cb00 23fd00
color2  #e7bdb7
color10 #ffdad5
#: yellow cecb00 fffd00
color3  #dfc38c
color11 #fcdfa6
#: blue 0d73cc 1a8fff
color4  #73342c
color12 #ffb4aa
#: magenta cb1ed1 fd28ff
color5  #5d3f3b
color13 #e7bdb7
#: cyan 0dcdcd 14ffff
color6  #574419
color14 #dfc38c
#: white dddddd ffffff
color7  #d8c2be
color15 #f1dedc

mark1_foreground #3b0906
mark1_background #ffdad5
mark2_foreground #2c1512
mark2_background #ffdad5
mark3_foreground #261a00
mark3_background #fcdfa6

active_tab_foreground #561e18
active_tab_background #ffb4aa
inactive_tab_foreground #ffdad5
inactive_tab_background #73342c

active_border_color #ffb4aa
inactive_border_color #561e18
# bell_border_color #ff5a00
