background            #0c0e13
foreground            #e2e2e9
cursor                #aec6ff
selection_background  #2c4678
selection_foreground  #d8e2ff

# Black
color0  #33353a
color8  #8e9099

# Red
color1  #ffb4ab
color9  #ffdad6

# Green
color2  #aec6ff
color10 #445e91

# Yellow
color3  #debcdf
color11 #583e5b

# Blue
color4  #2c4678
color12 #3f4759

# Magenta
color5  #e2e2e9
color13 #44474f

# Cyan
color6  #bfc6dc
color14 #aec6ff

# White
color7  #e2e2e9
color15 #2f3036
