include colors.conf

font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12 

disable_ligatures no

url_style curly

remember_window_size no
window_padding_width 10

background_opacity 0.90
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

sync_to_monitor no
map ctrl+shift+t new_tab_with_cwd
