# ==========    GENERAL    ==========

k           cycle ontop

# ==========    VIDEO    ==========

d           cycle deband
D           cycle deinterlace
n           playlist-next
N           playlist-prev
C           cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"

# ==========    AUDIO    ==========

a           cycle audio
A           cycle audio down
WHEEL_UP    add volume 2
WHEEL_DOWN  add volume -2
UP          add volume 2
DOWN        add volume -2
x           add audio-delay -0.05
X           add audio-delay +0.05

# ==========    PLAYBACK SPEED    ==========

s           cycle-values speed 0.25 0.5 0.75 1 1.25 1.5 1.75 2.0
S           set speed 1

# ==========    SUBTITLES    ==========

Shift+g     add sub-scale +0.05
Shift+f     add sub-scale -0.05
z           add sub-delay -0.05
Z           add sub-delay +0.05
u           cycle sub-gray
l           cycle-values sub-ass-override "scale" "force" "no"
