#!/bin/bash

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle >/dev/null

if pactl get-source-mute @DEFAULT_SOURCE@ | grep -q 'yes'; then
  osd_message='Microphone muted'
  osd_icon='microphone-sensitivity-muted-symbolic'
else
  osd_message='Microphone on'
  osd_icon='audio-input-microphone-symbolic'
fi

swayosd-client --custom-message "$osd_message" --custom-icon "$osd_icon"
