source = ~/.config/hypr/colors-hyprlock.conf

general {
    grace = 2
    ignore_empty_input = true
}

animation = fade, 1, 1.8, linear
bezier = linear, 1, 1, 0, 0

background {
    path = $image
    color = $background
    blur_passes = 2
}

input-field {
    placeholder_text = password
    size = 20%, 5%
    outline_thickness = 3
    inner_color = $primary

    outer_color = $on_background 45deg
    check_color = $secondary 120deg
    fail_color = $error 40deg

    font_color = $on_surface
    font_family = JetBrainsMono Nerd Font
    fade_on_empty = false
    rounding = 15

    position = 0, -130
    halign = center
    valign = center
}

label {
    font_family = JetBrainsMono Nerd Font
    text = cmd[update:0] echo "hello $USER how are you?"
    color = $on_surface_variant
    halign = center
    valign = center
    position = 0, -30
}

label {
    font_family = JetBrainsMono Nerd Font
    text = $TIME
    color = $on_surface_variant
    font_size = 100
    halign = center
    valign = center
    position = 0, 100
}

label {
    monitor =
    text = cmd[update:200] for f in /sys/class/leds/*capslock*/brightness; do [ "$(cat $f)" = "1" ] && echo "capslock is on btw"; done
    color = rgb(d79921)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, -220
    halign = center
    valign = center
}
