# Start your Quickshell unified shell automatically
exec-once = qs

# Start hypridle for idle management (lock, dpms, suspend)
exec-once = hypridle

# Add other autostarts here (notifications, wallpaper, etc.)
# exec-once = nm-applet &
exec-once = awww-daemon
exec-once = udiskie
exec-once = systemctl --user start hyprpolkitagent
