-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#111318",
  base01 = "#0c0e13",
  base02 = "#1a1b20",
  base03 = "#44474f",
  base04 = "#c5c6d0",
  base05 = "#e2e2e9",
  base06 = "#2f3036",
  base07 = "#37393e",

  base08 = "#d6abd7",
  base09 = "#debcdf",
  base0A = "#bfc6dc",
  base0B = "#aec6ff",
  base0C = "#583e5b",
  base0D = "#2c4678",
  base0E = "#3f4759",
  base0F = "#9ea9ca",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#2c4678',
  fg = '#d8e2ff', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#c588c6',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8e9099',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#debcdf',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#bfc6dc',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#445e91',
})
