-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#1a120d",
  base01 = "#140d08",
  base02 = "#221a15",
  base03 = "#52443c",
  base04 = "#d7c2b8",
  base05 = "#f0dfd7",
  base06 = "#382e29",
  base07 = "#413732",

  base08 = "#c4c081",
  base09 = "#ccc992",
  base0A = "#e5bfaa",
  base0B = "#ffb68c",
  base0C = "#4a481d",
  base0D = "#6f3812",
  base0E = "#5c4131",
  base0F = "#d9a283",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#6f3812',
  fg = '#ffdbc9', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#b4af5e',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9f8d84',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ccc992',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e5bfaa',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#8c4f27',
})
