-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#16130b",
  base01 = "#110e07",
  base02 = "#1f1b13",
  base03 = "#4d4639",
  base04 = "#cfc5b4",
  base05 = "#eae1d4",
  base06 = "#343027",
  base07 = "#3d392f",

  base08 = "#9ec69c",
  base09 = "#aecfac",
  base0A = "#d6c5a0",
  base0B = "#e6c26c",
  base0C = "#314d32",
  base0D = "#594400",
  base0E = "#51452a",
  base0F = "#c7af7c",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#594400',
  fg = '#ffdf95', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#7fb37c',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#989080',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#aecfac',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#d6c5a0',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#755b0b',
})
